services:
    nginx:
        container_name: nginx
        image: nginx:1.19.7-alpine
        restart: always
        volumes:
            - ../nginx:/etc/nginx/templates
    web-client:
        container_name: web-client
        build:
            context: ../../services/web-client
            args:
                NODE_IMAGE: node:15.11.0-alpine
        restart: always
        entrypoint: pnpm start
    api:
        container_name: api
        build:
            context: ../../services/api
            args:
                NODE_IMAGE: node:15.11.0-alpine
        restart: always
        environment:
            MONGO_HOST: mongo
            MONGO_DB_NAME: ${MONGO_DB_NAME}
            LOCAL_CLIENT_SECRET: ${LOCAL_CLIENT_SECRET}
            GMAIL_USERNAME: ${GMAIL_USERNAME}
            GMAIL_PASSWORD: ${GMAIL_PASSWORD}
            GMAIL_NAME: ${GMAIL_NAME}
        entrypoint: pnpm start
    mongo:
        container_name: mongo
        image: mongo:4.4.4
        restart: always
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ../../volumes/mongo:/data/db
